nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.4.cjs

# Prevent Yarn from symlinking the repo as a dependency in RTK
# https://yarnpkg.com/configuration/yarnrc#enableTransparentWorkspaces
enableTransparentWorkspaces: false
